- docs/_static/custom.css
- docs/index.rst
- docs/konfuzio.md
A note about the toctree: to fix the `<notitle>` issue I had to move the sub-toctrees from the various `crawler/docs/x/index.rst` files to the root `index.rst`. As a result, these sub-toctree files can be removed.
> Documentation improvements

- konfuzio_sdk/evaluate.py
- tests/test_data.py
- tests/test_evaluate.py
The "grouped" function in the evaluate.py in the SDK uses the mode to calculate the matching Annotation Set.
This does not work if the Tokenizer creates a large number of Spans that match correct Spans in the ground truth. Only because "correct" Spans are found, they should not be used for mode calculation as they have a confidence below label threshold.
> Changed: Use most frequent annotation_set_id from the high confidence Spans in the group, instead considering the correct Spans to be eligible to vote

- docs/sdk/contribution.md
We describe our internal SDK release process, as well as its integration stages with the Konfuzio Server, as documentation at https://dev.konfuzio.com/sdk/contribution.html#internal-release-process
> Added: Release process documentation

- konfuzio_sdk/data.py
- konfuzio_sdk/settings_importer.py
- tests/test_api.py
- tests/test_data.py
An environment variable (or an entry to the `.env` file) can now be used for disabling the creation of the log file.
> Changed: Log File creation can be disabled via an environment variable

- docs/sdk/contribution.md
Fixed a large typo in the documentation of our internal release process, where the release schedule for the Konfuzio Server was shifted by one week, and the DVUI schedule was missing.
See the updated documentation at https://dev.konfuzio.com/sdk/contribution.html#internal-release-process
> Fixed: Wrong documentation for Server/DVUI internal release process

- setup.py
This updates the [regex](https://pypi.org/project/regex/) package dependency from `regex==2020.6.8` to the latest version, for allowing the installation on machines that have no C++ compiler available.
> Changed: Dependency for the `regex` package updated to use the latest version

- konfuzio_sdk/data.py
- konfuzio_sdk/trainer/information_extraction.py
- tests/test_data.py
This fixes two bugs:
1. Occurring during an edge case for `Data.__eq__` when the ID of an object is 0
2. The other when both the filters `use_correct` and `ignore_below_threshold` are False in `AnnotationSet.annotations`.
These were causing the Konfuzio Server to filter out all Annotations belonging to default LabelSets in the extraction results.
[Python SDK docs - AnnotationSet](https://dev.konfuzio.com/sdk/sourcecode.html#annotation-set)
> Fixed: Two minor bugs that were wrongly filtering out Annotations when iterating through `AnnotationSet.annotations`

- .github/workflows/nightly.yml
- .github/workflows/python-app.yml
- .github/workflows/release.yml
Following [GitHub's recommendation](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/), we switch our runners to use `ubuntu-latest`, which now corresponds to Ubuntu 22.04.
> Changed: GitHub actions use Ubuntu 22.04

- konfuzio_sdk/data.py
- konfuzio_sdk/utils.py
- tests/test_regex.py
Fixed a bug in the Regex Generator for each Label, where some capture group names were duplicated. This was also causing a ValidationError during integration with the Konfuzio Server.
See the documentation at:
- [Python API docs - Label.find_regex](https://dev.konfuzio.com/sdk/sourcecode.html#label)
> Fixed: Bug in Automated Regex Generator that was producing duplicated capture group names

- .pre-commit-config.yaml
- konfuzio_sdk/settings_importer.py
- konfuzio_sdk/trainer/information_extraction.py
- tests/tokenizers/test_patterns.py
- tests/trainer/test_information_extraction.py
This fixes an error that arises when saving an RFExtractionAI model with the `include_konfuzio` option set to `True`. 
This also fixes a related issue where the local `Data` class `id_iter` counter would be reset to its value when saved potentially causing errors due to duplicated ids.
> Fix: "cannot pickle '_thread.RLock' object" error when saving with konfuzio_sdk

- konfuzio_sdk/trainer/document_categorization.py
- konfuzio_sdk/trainer/file_splitting.py
- konfuzio_sdk/trainer/information_extraction.py
- tests/trainer/test_information_extraction.py
This fixes a bug when loading an AI model, where we check that the interface of any AI (as well as potentially custom AIs) is compatible with either the `Trainer` class, the `AbstractCategorizationAI` class, or the `AbstractFileSplittingModel` class (which define the interfaces for Extraction AIs, Categorization AIs, and File Splitting AIs, respectively).
> Fixed: A bug when validating the interface of a loaded AI model

- tests/trainer/test_file_splitting.py
Multimodal File Splitting Model testcases are used to verify that the training pipeline is functional, which can be done with just a single training document and 2 epochs. Thus, the overall test suite now runs in about half the time.
> Fixed: Runtime of Multimodal File Splitting Model testcases which was longer than necessary

- konfuzio_sdk/data.py
- konfuzio_sdk/evaluate.py
- konfuzio_sdk/tokenizer/base.py
- konfuzio_sdk/trainer/information_extraction.py
- tests/trainer/test_information_extraction.py
This change will automatically set the `retokenize` option of the `RFExtractionAI.feature_function` to its assumed optimal value, if no value is set by the SDK user. If we use the Whitespace Tokenizer, we set it to True so that we only create training Annotations which the AI would actually encounter in practice. If we use a trained ListTokenizer, we set it to False so that the AI is trained to discriminate between correct Annotations and overlapping false positives. 
This also includes a change to the evaluation function allowing it to handle overlapping Annotations and ignore Annotations which are above detection threshold, but overlapping with an Annotation with a higher confidence.
> Changed: feature_function retokenize setting takes on a smart default value

- konfuzio_sdk/trainer/information_extraction.py
- tests/trainer/test_information_extraction.py
This fixes an issue where extracted Documents had two different default AnnotationSets included.
> Fixed: A minor bug that caused extracted Documents to have two different default AnnotationSets

- docs/glossary.md
- docs/sdk/sourcecode.rst
- konfuzio_sdk/data.py
- konfuzio_sdk/trainer/information_extraction.py
- tests/trainer/test_information_extraction.py
This fixes an error that occurred when the horizontal merge logic would create a Span identical to one already created by the Tokenizer, thereby creating a duplicate Annotation error when adding it to the Document.
> Fix: Duplicate Annotation error when extracting Document

- docs/web/api-v3.md
`mermaid` diagrams need an empty line or they are not rendered at all.
> Fix: mermaid diagram generation

- setup.py
This sets a maximum version to the pandas package to prevent the installation of pandas 2.x which is incompatible with the SDK. Compatibility with pandas 2.x will be added on April 28th.
> Changed: pandas version requirement updated to `pandas>=1.3.5,<2.0.0`

- docs/glossary.md
- docs/web/changelog_app.md
- konfuzio_sdk/data.py
- konfuzio_sdk/evaluate.py
- konfuzio_sdk/trainer/information_extraction.py
- tests/test_data.py
- tests/test_evaluate.py
When selecting Default Evaluation: After we have calculated the TPs, FPs, FNs for the Document, we filter out the case where a Label should only appear once per AnnotationSet but has been predicted multiple times. In this case, if any of the predictions is a TP then we keep one and discard FPs/FNs. If no TPs, if any of the predictions is a FP then we keep one and discard the FNs. If no FPs, then we keep a FN. The prediction we keep is always the first in terms of start_offset.
To see some examples of how it works in practice, see [Konfuzio Guide - Extraction AI Evaluation](https://help.konfuzio.com/modules/extractions/index.html#evaluation).
> Fixed: Default Evaluation filters out the case where a Label should only appear once per AnnotationSet

- konfuzio_sdk/data.py
- tests/trainer/test_file_splitting.py
Now Pages of sub-Documents after file splitting have the same Category as their counterparts in the original Document.
>  Changed: Pages of sub-Documents after file splitting inherit Categories of Pages in the original Document

- konfuzio_sdk/data.py
- konfuzio_sdk/trainer/document_categorization.py
- tests/trainer/test_document_categorization.py
Categorization was relying on `image_paths` to generate `Image` instances, but these are not always available. After https://github.com/konfuzio-ai/konfuzio-sdk/pull/270, however, we already have an `image` property on `Page` instances, which contains an `Image` instance that was built either from a file loaded from a path or from the bytes passed by the server, so this PR makes use of that property instead.
> Changed: Use images instead of image_paths

- docs/web/changelog_app.md
- konfuzio_sdk/trainer/document_categorization.py
- setup.py
- tests/trainer/test_document_categorization.py
* Reduce saved categorization pickle size by running `lose_weight` on the tokenizer
* Include `eval_transforms` and `train_transforms` in the saved pickle to ensure compatibility when loaded externally
> Changed: Additional data and `reduce_weight` in saved categorization pickle

- setup.py
Fixed an issue about spacy not running properly with the Python versions 3.10 and 3.11.
> Fixed: spacy's version conflict with Python 3.10 & 3.11

- konfuzio_sdk/data.py
- tests/test_evaluate.py
This fixes an error where the non-strict `ExtractionEvaluation` would throw a `ValueError` when it was used on a Document with no extractions.
> Fix: ValueError Exception with non-strict Evaluation and Empty Extracted Document

- konfuzio_sdk/data.py
- tests/test_data.py
When using `create_subdocument_from_page_range`, i.e. during splitting, the resulting Document's Pages did not retain the category annotations from the original Pages.
> Fixed: Retain category annotations in subdocuments

- docs/sdk/boilerplates/test_get_started.py
This fixes a bug in a boilerplate test that creates a test Document without deleting it at the end of the test.
> Fix: Delete boilerplate test Document

- konfuzio_sdk/trainer/document_categorization.py
- konfuzio_sdk/trainer/information_extraction.py
This removes obsolete WIP warnings in the training module.
> Removed: Top level WIP warnings in information extraction and document categorization files

- konfuzio_sdk/trainer/base.py
- tests/trainer/test_information_extraction.py
This fixes a bug where Custom Extraction AIs without Tokenizer were prevented from being saved.
> Fix: Bug preventing saving of custom Extraction AI with no Tokenizer

- .gitignore
- konfuzio_sdk/data.py
- I updated the `.gitignore` to include the following :
```
dist #due to setup from source
build #due to setup from source
.vscode #vscode config
tests/example_project_data #it was updated when I ran the tests
```
- There is no typo on the `from_image_size()` method ( check the comments on [this issue](https://git.konfuzio.com/konfuzio/objectives/-/issues/11448) ). Instead, I expanded the description of the method to be more intuitive:
```diff
+         Compute the coordinates of the bottom-left and the top-right corners in
+         a (down-to-up y-axis, left-right x-axis, page-scaled system).
+        :param: (x0,y0) and (x1,y1) are the coordniates of resp. the top-left and the bottom-right corners
+        in a (up-to-down y-axis, left-right x-axis, image-scaled) system.
```
> Fix: Bbox Class Method from_image_size()

- konfuzio_sdk/data.py
This removes a WIP warning in the `Span.bbox` method.
> Removed WIP warning in Span.bbox

- konfuzio_sdk/data.py
- tests/test_data.py
This changes the behavior of the Bbox validation to only log a warning when encountering a zero width or height Bbox.
> Changed: warning log for zero width/height Bbox

- konfuzio_sdk/data.py
- konfuzio_sdk/tokenizer/regex.py
- tests/test_data.py
- tests/test_evaluate.py
- tests/test_regex.py
* Change data structure for spans and annotations from list to dict
* Replace naive `in` checks with `dict.get`
* Ensure external interface (non-private functions) stay consistent
* Fix tests that checked private properties directly
> Fixed: Optimize spans/annotations data structures

- docs/web/changelog_app.md
The date-time tag of the release has to be updated. It still says 'Next release..', but I assume that this might be automatic.
> Update changelog_app.md for the release on 18.10.2023

- konfuzio_sdk/normalize.py
- tests/test_normalize.py
Values like '1.23.4' are now normalized to None.
> Added: Normalization of values like '1.23.4' to None

- konfuzio_sdk/trainer/file_splitting.py
Added: a condition that page must be non empty before considering it as a `first_page`
> Fixed: Split on Blank Page

- konfuzio_sdk/cli.py
- konfuzio_sdk/data.py
- tests/test_cli.py
Now there is no error when a user passes a URL with a trailing slash in the end (e.g. https://app.konfuzio.com/).
> Fixed: Trailing slashes at the end of the URLs passed at konfuzio_sdk init

- docs/sdk/sourcecode.rst
- docs/sdk/tutorials/build-context-aware-file-splitting-model/index_nb.md
- docs/sdk/tutorials/context-aware-file-splitting-model/index_nb.md
- docs/sdk/tutorials/outlier-annotations/index_nb.md
- docs/sdk/tutorials/tokenizers/index_nb.md
Fixed nonfunctional links in tutorials' footers, modified obsolete API references, changed image size for wrongly rendered output with Bboxes.
> Fixed: links in the documentation, image size in tokenizer output visualization

- konfuzio_sdk/trainer/information_extraction.py
- tests/trainer/test_information_extraction.py
> Added: functionality to tune hyperparameters for Label Set classifier independently

- docs/sdk/tutorials/data-preparation/index_nb.md
- docs/sdk/tutorials/example-usage/index_nb.md
- docs/sdk/tutorials/tokenizers/index_nb.md
- documents used in test pipelines are removed using meaningful properties instead of accessing them by indices
> Fixed: removing documents by indices instead of meaningful properties

- konfuzio_sdk/data.py
Fixed the issue that caused documents to not receive correct categories and not build project properly when initalized in the SDK.
> Fixed: variable name doubling resulting in incorrect category assignment

- konfuzio_sdk/trainer/information_extraction.py
> Changed: slugify category name when saving bento model

- konfuzio_sdk/bento/extraction/rfextractionai_service.py
- konfuzio_sdk/bento/extraction/utils.py
- konfuzio_sdk/trainer/information_extraction.py
> Changed: Bento optimizations

- konfuzio_sdk/api.py
- setup.py
- tests/test_api.py
> Changed: use python-dotenv to write the env file

- konfuzio_sdk/trainer/information_extraction.py
- tests/trainer/test_information_extraction.py
> Fixed: limit pkl_name to 63 characters

- konfuzio_sdk/data.py
- konfuzio_sdk/evaluate.py
- konfuzio_sdk/settings_importer.py
- konfuzio_sdk/utils.py
- pytest.ini
- setup.py
- tests/test_evaluate.py
For the moment, and from a strategic perspective, there was no legitimate reason to make a big change to the Extraction AI Evaluation, instead we could just log a warning about the inconsistent evaluation results for Custom Extraction AIs that are not applying the right post-processing to their predictions.
> Revert "Fixed: inconsistent evaluation of Spans containing more than one word"

- konfuzio_sdk/bento/categorization/categorizationai_service.py
- konfuzio_sdk/bento/extraction/rfextractionai_service.py
- konfuzio_sdk/bento/extraction/rfextractionai_service_for_legacy_trainer.py
Also cleanup of legacy_trainer service (sort imports; `document` was undefined).
> Added: customize timeout and max_concurrency in services via env vars
