docs/_templates/layout.html
Reverts konfuzio-ai/document-ai-python-sdk#52
=> Revert "add osano"

docs/web/api_guides.md, docs/web/api_v3.md
Initial draft of API v3 documentation. As it's prerelease material, there's no link yet in the sidebar.
=> API v3 docs

konfuzio_sdk/data.py, konfuzio_sdk/trainer/information_extraction.py, tests/test_api.py, tests/test_data.py, tests/test_evaluate.py, tests/tokenizers/test_base.py, tests/trainer/test_information_extraction.py
Added: Option to force projects, documents, and related data in offline mode.
=> Force data in offline mode

konfuzio_sdk/evaluate.py, tests/test_evaluate.py
Needed for non-strict evaluation from the server.
=> Allow setting the strict parameter when initializing Evaluation

docs/web/api-v3.md
To be merged after https://gitlab.com/konfuzio/text-annotation/-/merge_requests/372 is also merged.
=> Cleanup API v3 docs; add bbox documentation

docs/web/api-v3.md
=> Update api-v3.md: file extension limits

konfuzio_sdk/trainer/information_extraction.py
This removes the catchphrase and substring features for feature extraction.
See [Removed Extraction AI Parameters](https://help.konfuzio.com/modules/categories/index.html#removed-extraction-ai-parameters)
=> Removed: Catchphrase and substring features

.github/workflows/python-app.yml, docs/sdk/boilerplates/test_get_started.py, docs/sdk/examples/intro.md, konfuzio_sdk/api.py, konfuzio_sdk/data.py, konfuzio_sdk/trainer/information_extraction.py, tests/test_data.py
This replaces the `from_file_async` and `from_file_sync` methods with a single `from_file` method returning with a `sync` parameter returning a Document object. This also allows for more targeted updating of specific Documents in a Project.
=> Changed: `Document.from_file` method to upload files to a Konfuzio instance

docs/web/api-v3.md
Documentation for https://git.konfuzio.com/konfuzio/objectives/-/issues/9842 and https://git.konfuzio.com/konfuzio/objectives/-/issues/9808
=> Added: Additional API guides

docs/sdk/boilerplates/test_document_categorization.py, docs/sdk/index.md, konfuzio_sdk/trainer/document_categorization.py, tests/trainer/test_document_categorization.py
Changed the format accepted as an input at Categorization AI's `fit()` method; set default values to the `batch_size` and `max_len` arguments.
=> Changed: Default input parameters for the Categorization AI's fitting

docs/dvui/explanations.md
Changed words in upper case to lower case and updated port number.
=> Fixes for consistency in DVUI explanations

docs/conf.py, docs/sdk/boilerplates/test_paragraph_extraction_ai.py, docs/sdk/examples/information_extraction/index.md, docs/sdk/examples/paragraph_and_sentence_tokenizer/index.md, konfuzio_sdk/trainer/information_extraction.py, tests/trainer/test_information_extraction.py
This adds the example of the Paragraph Extraction AI to the Custom AI creation documentation.
=> Added: Paragraph Extraction AI code example

docs/sdk/boilerplates/test_custom_categorization_ai.py, docs/sdk/boilerplates/test_custom_extraction_ai.py, konfuzio_sdk/evaluate.py, konfuzio_sdk/settings_importer.py
Fixed the value of NO_CATEGORY's ID expected upon evaluation: it is 0, not -1.
=> Fixed: ID of NO_CATEGORY expected upon evaluation

docs/sdk/tutorials/document_categorization/index.md, extras_list.py, konfuzio_sdk/data.py, konfuzio_sdk/tokenizer/paragraph_and_sentence.py
Change versions of `torch`, `torchvision` and `transformers` to avoid incompatibility between each other and with different python versions.
=> Changed: versions of AI-related dependencies

docs/sdk/home/index.md, docs/sdk/tutorials/index.md, konfuzio_sdk/data.py
This adds documentation explaining the Document.dataset_status and Document.status attributes.
=> Added: Document status documentation

konfuzio_sdk/trainer/document_categorization.py
Fixed the ability to use BERT models as text-processing components in Categorization AI.
=> Fix: Usage of BERT models for Categorization AI's text component

konfuzio_sdk/trainer/document_categorization.py
Fixed the possibility to use text module of Categorization independently from image module.
=> Fix: Independent usage of Categorization's text module

konfuzio_sdk/trainer/document_categorization.py
```diff 
- logger.info(f'test_loss: {np.mean(train_losses):.3f}, test_acc: {np.nanmean(train_loss):.3f}')
```
```diff 
+            f1_score = f1_metric.compute(predictions=predictions_list, references=ground_truth_list, average="macro")[
+                "f1"
+            ]  # compute f1 score
+            acc_score = acc_metric.compute(predictions=predictions_list, references=ground_truth_list)[
+                "accuracy"
+            ]  # compute accuracy score
```
```diff 
+ logger.info(
+                f'Epoch: {epoch + 1} | '
+                f'Train Loss: {np.mean(train_loss):.3f} | '
+                f'Train F1: {f1_score:.3f} | '
+                f'Train Accuracy: {acc_score:.3f} |'
+          )
```
=> Reworked Categorization AI Training Logs

konfuzio_sdk/api.py, tests/test_api.py
…does not have access to certain AIs due to permission settings.
=> Snapshot creation still takes place if the user has no permissions

docs/sdk/tutorials/information_extraction/index_nb.md, docs/sdk/tutorials/outlier-annotations/index_nb.md, docs/sdk/tutorials/regex_based_annotations/index_nb.md, docs/sdk/tutorials/set-category-manually/index_nb.md
Added print() statements to the code cells to produce a meaningful output. Removed folders that contained empty Markdown files or were empty.
=> Changed: Outputs in documentation and removing obsolete folders

konfuzio_sdk/data.py, tests/test_data.py
Added a method to view Annotation Sets of Annotations present in the Page.
=> Added: Page.annotation_sets() method

.pre-commit-config.yaml, docs/conf.py, konfuzio_sdk/data.py, konfuzio_sdk/tokenizer/base.py, konfuzio_sdk/trainer/document_categorization.py, tests/test_cli.py, tests/test_normalize.py, tests/trainer/test_document_categorization.py, tests/trainer/test_tokenization.py
Force ruff format in pre-commit and format additional files that missed the first formatting round.
=> Fixed: Force ruff format

.github/workflows/python-app.yml, docs/sdk/tutorials/data-preparation/index_nb.md
Removed an explicitly imported test variable used as a placeholder from the tutorial about the data preparation.
=> Removed: explicit import of test variable

konfuzio_sdk/normalize.py, tests/test_normalize.py
Added normalization for edge case of ranges like '12,3-15.4' and a general fix for all unnormalizeable floats.
=> Added: normalization for ranges like '12,3-15.4'

konfuzio_sdk/api.py
Fix a bug where the only one AI model was being included in the Snapshot rather than all active AI's of the project.
=> Bugfix for AI Model inclusion into the Snapshot

docs/sdk/tutorials.rst, docs/sdk/tutorials/create-annotations-api/index_nb.md, docs/sdk/tutorials/outlier-annotations/index_nb.md, docs/sdk/tutorials/regex_based_annotations/index_nb.md, docs/sdk/tutorials/tokenizers/index_nb.md, konfuzio_sdk/data.py, tests/test_data.py
Fixed errors that prevented documentation from proper rendering and backward compatibility bugs related to Page and Bboxes.
=> Fixed: backward compatibility in Page class and code in tutorials

docs/sdk/tutorials/_tutorial_template.md, docs/sdk/tutorials/annual-reports/index_nb.md, docs/sdk/tutorials/async_upload_with_callback/index_nb.md, docs/sdk/tutorials/barcode-scanner/index_nb.md, docs/sdk/tutorials/build-context-aware-file-splitting-model/index_nb.md, docs/sdk/tutorials/context-aware-file-splitting-model/index_nb.md, docs/sdk/tutorials/create-annotations-api/index_nb.md, docs/sdk/tutorials/create-custom-categorization-ai/index_nb.md, docs/sdk/tutorials/create-custom-splitting-ai/index_nb.md, docs/sdk/tutorials/data-preparation/index_nb.md, docs/sdk/tutorials/data_validation/index_nb.md, docs/sdk/tutorials/document_categorization/index_nb.md, docs/sdk/tutorials/example-usage/index_nb.md, docs/sdk/tutorials/file-splitting-evaluation/index_nb.md, docs/sdk/tutorials/information_extraction/index_nb.md, docs/sdk/tutorials/ner-ontonotes-fast/index_nb.md, docs/sdk/tutorials/outlier-annotations/index_nb.md, docs/sdk/tutorials/pdf-form-generator/index_nb.md, docs/sdk/tutorials/regex_based_annotations/index_nb.md, docs/sdk/tutorials/rf-extraction-ai/index_nb.md, docs/sdk/tutorials/set-category-manually/index_nb.md, docs/sdk/tutorials/tokenizers/index_nb.md, docs/sdk/tutorials/upload-your-ai/index_nb.md, notebooks/Quick_start_template_for_Konfuzio_SDK.ipynb, notebooks/README.md
Added: Quick start notebook (Google Colab)
Added: Environment section with link to the SDK installation docs and the quick start notebook
=> Added: quick start notebook and installation link to tutorials

README.md
Changed the formatting of emojis in the README for proper displaying on pypi, fixed broken/obsolete links.
=> Fixed: emojis used in README for proper display in pypi

docs/sdk/sourcecode.rst, konfuzio_sdk/api.py, konfuzio_sdk/trainer/base.py
Added the previously missing classes and methods from undescribed submodules into the API reference section of the documentation.
=> Added: undescribed classes and methods from the SDK's submodules

notebooks/Get_started_with_the_Konfuzio_SDK.ipynb
Fixed: Get projects as list
Changed: Installation check
=> Changed: Installation check

docs/sdk/tutorials/tokenizers/index_nb.md, tests/test_api.py, tests/test_data.py, tests/trainer/test_information_extraction.py
- Replaced missing document from tests where it was used with a newer one.
- Added new fields missing from API tests.
- Relaxed requirements for a project size test.
=> Changed: replaced a removed document's ID with a newly uploaded one
